### PR TITLE
HTML-384: Added support for ajax autocomplete provider to EncounterPr…

### PR DESCRIPTION
**Pull request by mhawila**
…oviderAndRole tag. To accomplish this I have added support for two attributes.

1. autocompleteProvider which can take values true/false (Dafault is false)
2. providerMatchMode which is used to specifiy how matching is done when the text to be searched is submitted via ajax. This takes one of the three
   values namely "START", "END", "ANYWHERE" with "START" as default.

Matching is done per standard OpenMRS API (i.e. via ProviderService).

### CODE REVIEW

**Comment by mogoodrich** [comment]
@mhawila  this looks like it is the just the commit from earlier the week (says 4 days ago) that already merged?

**Comment by mhawila** [comment]
I made changes and push to the same branch. I didn't change the commit message because the change was essentially a minor fix.

**Comment by mogoodrich** [comment]
@mhawila hmm... so this isn't working for me.  Did you just somehow amend the existing commit?  Because I'm only seeing one commit in this pull request from 5 days ago.  It is unable to be automatically merged because I already merged into your existing commit, so there's a conflict.

I tried testing locally and overwriting all your old changes with your new ones, but the autocomplete isn't working for me.  I'm seeing these errors in the JS console:

 Uncaught SyntaxError: Unexpected end of input
2Uncaught ReferenceError: setupProviderAutocomplete is not defined

**Comment by mhawila** [comment]
I made a terrible mistake!! Somehow I forgot I already submitted these changes to the upstream so I did a rebase. That is why this is happening. I think the best way is just to ignore this commit. I will work of master to fix that display issue. by the way this autocomplete widget is driving me crazy, I am having trouble making it do exactly what I want. I will comment on the ticket about the challenges I am facing.

**Comment by mogoodrich** [comment]
Just catching up after being off for a few days last week... are you waiting on me for anything here?

**Comment by mhawila** [comment]
Mark we agreed to discard this commit because I messed up the code by doing a rebase after the initial pull request.

**Comment by mogoodrich** [comment]
Right...just wondering if there was another commit I was missing... no worries if you haven't gotten to it yet, just wanted to make sure you weren't waiting on me.

**Pull request closed without merging**
